name: cinema_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.2

  firebase_core: ^2.6.0

  injectable: ^1.5.3
  get_it: ^7.2.0

  dio: ^5.1.1
  http:

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.0.0
  provider: ^6.0.0

  shared_preferences: ^2.0.0
  hive: ^2.0.0

  intl:


  json_annotation: ^4.7.0

  animate_do: ^2.0.0
  animated_text_kit: ^4.0.0
  page_transition: ^2.0.0

  responsive_sizer: ^3.0.0

  logger: ^1.0.0
  pretty_dio_logger: ^1.0.0
  form_validator:

  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0
  widget_to_marker: ^1.0.0

  dropdown_button2: ^1.0.0
  smooth_page_indicator:
  carousel_slider: ^4.0.0
  animated_custom_dropdown:
  sliver_tools:
  toastification:
  easy_loading_button:
  expandable: ^5.0.0
  toggle_switch: ^2.0.0
  lottie: ^1.0.0
  fluttertoast: ^8.0.0
  google_fonts: ^2.0.0
  path_provider: ^2.0.0
  connectivity_plus: ^1.0.0
  flutter_easyloading:
  loading_animation_widget: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  hive_generator: ^2.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7

  flutter_lints: ^2.0.0
  json_serializable: ^6.1.4
  flutter_gen:

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/test/
    - assets/maps/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
